name: test-compare-stock-symbols

on:
  schedule:
    - cron: '0 1 * * *'  # Runs every day at 8 AM UTC / 1 AM PDT
  workflow_dispatch: 
    inputs:
      run_option:
        description: 'Choose the pytest run option'
        required: true
        default: 'pytest -s'
        type: choice
        options:
          - 'pytest -s'
          - 'pytest --set-to-run=not_in_test -s'
          - 'pytest --set-to-run=not_in_actual -s'
          
jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests (manual)
        if: github.event_name == 'workflow_dispatch'
        run: ${{ inputs.run_option }}

      - name: Run tests (scheduled)
        if: github.event_name == 'schedule'
        run: pytest -s
